<a href="https://colab.research.google.com/github/santhimaddipudi/Python-work/blob/master/numpy_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Numpy**

In [2]:
import numpy as np
n1=np.array([1,2,3])
print(n1)

[1 2 3]


In [4]:
n2=np.zeros(10)
print(n2)
n3=np.ones((5,5))
print(n3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
print(np.eye(5))#5x5 matrix with 1 in diagnal

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
#2d array
b=np.array([[1,2,3],[4,5,6]])
print(b)
#3d array
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[5,4,3]]])
print(c)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [5 4 3]]]
