<a href="https://colab.research.google.com/github/santhimaddipudi/Python/blob/master/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#creates a diagnal array
import numpy as np
np.diag((2,3,4,5))

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [3]:
np.random.seed(100) # Set seed
ar11=np.random.rand(3); ar11

array([0.54340494, 0.27836939, 0.42451759])

In [4]:
#create an uninitialized array
ar13=np.empty((3,2)); ar13

array([[4.81078028e-310, 0.00000000e+000],
       [2.05833592e-312, 6.79038654e-313],
       [2.14321575e-312, 2.27053550e-312]])

In [7]:
#allows one to construct an array from a smaller array by repeating it several times on the basis of a parameter:
a1=np.tile(np.array([[1,2],[6,7]]),3)
print(a1)
a2=np.tile(np.array([[1,2],[6,7]]),(2,2))
print(a2)

[[1 2 1 2 1 2]
 [6 7 6 7 6 7]]
[[1 2 1 2]
 [6 7 6 7]
 [1 2 1 2]
 [6 7 6 7]]
