<a href="https://colab.research.google.com/github/santhimaddipudi/Python-work/blob/master/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from numpy.linalg import eig
a = np.array([[0, 2],
              [2, 3]])
print(a)
w,v=eig(a)
print('E-value:', w)
print('E-vector', v)


[[0 2]
 [2 3]]
E-value: [-1.  4.]
E-vector [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


In [23]:
#REMAKE ORIGINAL WITH svd
import numpy as np

#Creating a matrix A
A = np.array([[3,4,3],[1,2,3],[4,2,1]])
print(A)
u,v=np.linalg.eig(A)
print(v)
#Performing SVD
U, D, VT = np.linalg.svd(A)
print("U value:",U)
print("D value:",D)
print("V value:",VT)

#Checking if we can remake the original matrix using U,D,VT
A_remake = (U @ np.diag(D) @ VT)
print(A_remake)

[[3 4 3]
 [1 2 3]
 [4 2 1]]
[[ 0.71702664+0.j          0.01961888-0.3440499j   0.01961888+0.3440499j ]
 [ 0.42048072+0.j          0.57135858+0.33513653j  0.57135858-0.33513653j]
 [ 0.55593953+0.j         -0.66518994+0.j         -0.66518994-0.j        ]]
U value: [[-0.73553325 -0.18392937 -0.65204358]
 [-0.42657919 -0.62196982  0.65664582]
 [-0.52632788  0.76113306  0.37901904]]
D value: [7.87764972 2.54031671 0.69958986]
V value: [[-0.60151068 -0.61540527 -0.5093734 ]
 [ 0.73643349 -0.18005275 -0.65210944]
 [ 0.30959751 -0.76737042  0.5615087 ]]
[[3. 4. 3.]
 [1. 2. 3.]
 [4. 2. 1.]]


In [18]:
d=[1,2,3]
np.diag(d)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])