<a href="https://colab.research.google.com/github/santhimaddipudi/Python/blob/master/Vectors_and_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
#vector--1D
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [5]:
x.shape

(4,)

In [8]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
a.shape

(3, 2)

In [10]:
#TRANSPOSE
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [11]:
2+a#add scalar to every element in matrix(braodcast)

array([[3, 4],
       [5, 6],
       [7, 8]])

In [12]:
a1=np.array([[2,3,4],[1,2,3],[3,5,6]])
b1=np.array([[1],[2],[3]])
print(a1)
print(b1)

[[2 3 4]
 [1 2 3]
 [3 5 6]]
[[1]
 [2]
 [3]]


In [13]:
print(a1+b1)

[[3 4 5]
 [3 4 5]
 [6 8 9]]


In [14]:
c1=np.array([1,1,1])#python will broadcast the array with other array
print(a1+c1)

[[3 4 5]
 [2 3 4]
 [4 6 7]]


In [16]:
print((a1+c1).shape)

(3, 3)


In [21]:
e=np.array([[1,0],[0,1]])
e
np.linalg.inv(e)

array([[1., 0.],
       [0., 1.]])

In [51]:
#yield element wise multiplication known as the Hadamard Product
a1=np.array([[1,2],[2,3]])
a2=np.array([[1,3],[3,3]])
#print(a1@a2) #matrix multiplication
print(a1*a2) #Hadamard Product,same as below--element wise multiplication
#np.multiply(a1, a2)#Hadamard Product

[[1 6]
 [6 9]]


In [35]:
#dot product
a1=np.array([[1,2],[2,3]])
a2=np.array([[1,3],[3,3]])
print(a1)
print(a2)
np.dot(a1,a2)

[[1 2]
 [2 3]]
[[1 3]
 [3 3]]


array([[ 7,  9],
       [11, 15]])

In [34]:
np.dot(a2,a1)

array([[ 7, 11],
       [ 9, 15]])

In [61]:
#dot product of two diffrent dim matrixes
m1=np.array([[1,2],[2,3]])
m2=np.array([[1,2,1],[1,2,3]])
print(np.dot(m1,m2)) #dot product
print(m1@m2) #Matrix product

[[ 3  6  7]
 [ 5 10 11]]
[[ 3  6  7]
 [ 5 10 11]]


In [42]:
#dot product of vectors is scalar value
import numpy as np

v = np.array([1,2,3])
u = np.array([3,2,4])

print(np.dot(v,u))

19


In [43]:
#scalar with array
r=2
np.dot(r,u)

array([6, 4, 8])

In [62]:
h1=np.array([[3,4,5],[6,7,8]])
h2=np.array([[1,2],[3,4],[5,1]])
print(h1@h2)#matrix product
print(h2@h1)#matrix product


[[40 27]
 [67 48]]
[[15 18 21]
 [33 40 47]
 [21 27 33]]


##cross product

In [76]:
# import library
import numpy as np

# declare vectors
x = [1, 2]
y = [3, 4]

# find cross product of
# two given vectors
result = np.cross(x, y)

# show the result
print(result)

-2


In [89]:
# import library
import numpy as np

# declare vectors
x = [[1,2], [8,4]]
y = [[2,1], [3,2]]

# find cross product of
# two given vectors
print(x)
print(y)
result = np.cross(x, y)#1x1-2x2,8x2-3X4=>-3,4


# show the result
print(result)


[[1, 2], [8, 4]]
[[2, 1], [3, 2]]
[-3  4]


In [94]:
# Example 3: One Vector 2D
arr = np.array([2,4,2])
arr1 = np.array([3,5,2])
print(np.cross(arr, arr1))
print(np.cross(arr1, arr))

[-2  2 -2]
[ 2 -2  2]


In [96]:
#L1 norm
arr = np.array([1,2,3,4])
np.linalg.norm(arr,1) #1+2+3+4

10.0

In [97]:
#L1 norm
arr = np.array([-1,2,-3,4])
np.linalg.norm(arr,1) #|-1|+|2|+|-3|+|4|  absolute values

10.0

In [103]:
#L2 norm
arr2 = np.array([1,2,3,4,5])
np.linalg.norm(arr2)#sqrt(1^2 + 2^2 + 3^2 + 4^2 + 5^2) = 7.416
# same as
#np.linalg.norm(arr2,2)

7.416198487095663

##Matrix Inversion

In [114]:
# Import required package
import numpy as np

# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


###SVD -Singular Value Decomposition

In [115]:
#svd
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.svd(m1)

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))

In [124]:
#svd
m1 = np.array([[1,8],[3,5]])
np.linalg.svd(m1)

(array([[-0.81826243, -0.57484485],
        [-0.57484485,  0.81826243]]),
 array([9.75747479, 1.94722512]),
 array([[-0.2605999 , -0.96544689],
        [ 0.96544689, -0.2605999 ]]))

##Covariance matrix


In [131]:
m1 = np.array([[1,2],[9,6]])
np.cov(m1)

array([[ 0.5, -1.5],
       [-1.5,  4.5]])

In [133]:
x = np.array([[0, 2], [1, 1], [2, 0]]).T
print(x)
np.cov(x)

[[0 1 2]
 [2 1 0]]


array([[ 1., -1.],
       [-1.,  1.]])

In [139]:
import numpy as np

A = [45, 37, 42, 35, 39,78,88,32,21]
B = [38, 31, 26, 28, 33,88,35, 39,78]
C = [10, 15, 17, 21, 12,76,35, 39,78]

data = np.array([A, B, C])
print(data)
cov_matrix = np.cov(data, bias=True)
print(cov_matrix)

[[45 37 42 35 39 78 88 32 21]
 [38 31 26 28 33 88 35 39 78]
 [10 15 17 21 12 76 35 39 78]]
[[430.66666667  77.55555556  86.33333333]
 [ 77.55555556 456.         495.22222222]
 [ 86.33333333 495.22222222 622.66666667]]


###determinant

In [141]:
import numpy as np
a = np.array([[1,2], [3,4]])
print(np.linalg.det(a))

-2.0000000000000004


In [143]:
import numpy as np

b = np.array([[6,1,1], [4, -2, 5], [2,8,7]])
print(b)
np.linalg.det(b)
##print 6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]


-306.0

###Rank of matrix

In [144]:
matrixA = np.array([[1, 2, 3, 23],
                       [4, 5, 6, 25],
                       [7, 8, 9, 28],
                       [10, 11, 12, 41]])
np.linalg.matrix_rank(matrixA)

3

In [153]:
my_matrix = np.array([[1, 2, 1], [2, 4,3], [3, 6, 3]])
print("Matrix",my_matrix)
np.linalg.matrix_rank(my_matrix) #In the above example, we can note that row3 can be obtained by multiplying row1 by 3
 #other rows we can't get like that so rank is 2//same applies to columns


Matrix [[1 2 1]
 [2 4 3]
 [3 6 3]]


2